#ifndef MEDIAPLAYERCORE_GLOBAL_H
#define MEDIAPLAYERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEDIAPLAYERCORE_LIBRARY)
#  define MEDIAPLAYERCORE_EXPORT Q_DECL_EXPORT
#else
#  define MEDIAPLAYERCORE_EXPORT Q_DECL_IMPORT
#endif


#endif // MEDIAPLAYERCORE_GLOBAL_H
